language: java
jdk:
#  - oraclejdk8
#  - oraclejdk7
#  - openjdk7
   - openjdk6

script: mvn clean package -Dgpg.skip=true

notifications:  
  email:  
    recipients:  
      - gerald.chen.hz@gmail.com  
    #on_success: [always|never|change]  default: change  
    #on_failure: [always|never|change]  default: always  